### ISSUE TITLE
安卓小白毕设求救

### ISSUE THREAD

**Issue by SingleDolphin** [gs666/remusicX#3]
请问一下，项目目录外的build.gradle中的dependencies{com.android.support.appcompat-v7还有另一个com.android.support.design}这两行下面标记红线，怎么设置成对应的版本呢？
不胜感激

**Comment by gs666** [comment]
sync 就行了吧，如果这个版本你没有，IDE会自动下载

**Comment by SingleDolphin** [comment]
Thanks,想了解一下这个项目的数据库是怎么运作的，我已经在模拟器上跑起来了，If possible,can you add my wechat gc1078831245 to guide me to understand this project? I'll appreciate your help. I'm willing to donate your help.Thank u so much! 555
